### ISSUE TITLE
Direct linking to contract page ruins layout

### ISSUE THREAD

**Issue by ethernomad** [DigixGlobal/doxity#6]
If I go to http://solidity-apis.link-blockchain.org/ and click on Contracts it looks like this:
![screenshot from 2016-11-09 15-54-08](https://cloud.githubusercontent.com/assets/161566/20132302/e7dc74d0-a694-11e6-8ddd-464443c837cb.png)

But if I reload the page or link directly to the URL it looks like this:
![screenshot from 2016-11-09 15-54-22](https://cloud.githubusercontent.com/assets/161566/20132320/fbb9a55e-a694-11e6-971e-2ad7455409dc.png)

**Comment by hitchcott** [comment]
I had this issue some time ago but I believe it was fixed in the sample repo here: https://github.com/DigixGlobal/doxity-gatsby-starter-project

It's probably the case you have an old version of the boilerplate project, which you can re-clone the by using `doxity init` (and then `doxity build`).

I think perhaps some auto-updating versioning system might be a good solution here.

**Comment by hitchcott** [comment]
This has been fixed, you'll need to re-clone the boilerplate project.

Use `doxity init`, `doxity build`.

**Comment by ethernomad** [comment]
Great - this is fixed!
